// Constants for client status options and service categories
export const STATUS_OPTIONS = ["ACTIVE", "CLEARED", "LEFT", "INACTIVE", "PENDING"];

export const CLIENT_TYPES = ["TAX", "LEGAL"] as const;

export const SERVICE_CATEGORY_GROUPS: Record<string, string[]> = {
  "Intellectual Property (IPO)": [
    "Trademark Registration",
    "Trademark Renewal",
    "Trademark Opposition / Defense",
    "Copyright Registration",
    "Design Registration",
    "Patent Filing & Registration",
    "IPO General Consultation",
  ],
  "Corporate / SECP": [
    "Private Limited Company Registration",
    "Single Member Company (SMC) Registration",
    "Public Limited Company Registration",
    "Association of Persons (AOP) Registration",
    "Limited Liability Partnership (LLP) Registration",
    "Sole Proprietorship Registration",
    "NGO / Section 42 Company Registration",
    "Trust Registration",
    "Society Registration",
    "Foreign Company Registration",
    "Company Name Reservation",
    "Annual Returns Filing (SECP)",
    "Director / Shareholder Changes",
    "Share Transfer / Allotment",
    "Registered Office Change",
    "MOA / AOA Amendment",
    "Company Status Conversion",
    "Company Restoration / Strike-Off",
    "SECP General Compliance",
  ],
  "Taxation — FBR": [
    "NTN Registration (Individual)",
    "NTN Registration (AOP / Company)",
    "Income Tax Return Filing",
    "Withholding Tax Statement",
    "Tax Audit Representation",
    "Tax Appeal & Litigation",
    "Tax Notice Response",
    "Tax Exemption Certificate",
    "Filer Status Verification / Active Taxpayer",
    "FBR General Consultation",
  ],
  "Sales Tax": [
    "Sales Tax Registration (FBR - Federal)",
    "Sales Tax Return Filing (Federal)",
    "PRA Registration (Punjab Revenue Authority)",
    "PRA Sales Tax Return Filing",
    "SRB Registration (Sindh Revenue Board)",
    "SRB Sales Tax Return Filing",
    "KPRA / BRA Registration & Filing",
    "Sales Tax General Consultation",
  ],
  "Chamber of Commerce & Registrations": [
    "Chamber of Commerce Membership",
    "Chamber of Commerce Certificate",
    "WEBOC Registration",
    "Import / Export License (TDAP)",
    "PSQCA Certification",
    "Drug Registration (DRAP)",
    "Food Authority License",
    "PEMRA License",
    "PEC Registration",
    "PPRA / Tender Registration",
    "Other Regulatory Registration",
  ],
  "Legal Services": [
    "Drafting Legal Agreements & Contracts",
    "Legal Opinion / Advisory",
    "Legal Notice Drafting & Service",
    "Court Representation & Litigation",
    "Arbitration & Mediation",
    "Property / Real Estate Matters",
    "Family Law Matters",
    "Criminal Law Matters",
    "Banking & Finance Law",
    "Employment & Labour Law",
    "Immigration & Visa Matters",
    "Certified Oath Commissioner",
    "Official Notary Public",
    "Power of Attorney / Affidavits",
    "General Legal Consultation",
  ],
  "Other Services": [
    "Business Valuation & Audit",
    "Accounting & Bookkeeping",
    "Financial Advisory",
    "Insurance Claims",
  ],
};

// Flat list for backward compatibility
export const SERVICE_CATEGORIES = Object.values(SERVICE_CATEGORY_GROUPS).flat();
